name: Continuous Integration

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ temurin@1.8 ]
        scala: [ "2.12.15", "2.13.10" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt}

      - name: Compile
        run: sbt "++${{ matrix.scala }} compile"

      - name: Run tests
        run: sbt "++${{ matrix.scala }} coverage test"
